### ISSUE TITLE
Array Index Out of Bound Exception

### ISSUE THREAD

**Issue by gladtbx** [hekeki/cryptolib#1]
https://github.com/dirkgerhardt/cryptolib/blob/ae2e46c5baf233a0c9de878bd1bca808bcdef6b0/src/main/kotlin/com/hekeki/cryptolib/skc/AES.kt#L172

i+j is out of the array bound. 

Did you miss the modulation here?

**Comment by dirkgerhardt** [comment]
Do you have an example, to reproduce this?

**Comment by hekeki** [comment]
@gladtbx, thank you for your report.
I was not able to reproduce this issue without an example. 
If you'd like to update it, please reopen the issue.
